# -*- coding: utf-8 -*-
"""Pyomo process optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHCJAorCsrlBQH3GBrfqDQi-XNXU6lXt
"""

!pip install pyomo idaes-pse --quiet
!idaes get-extensions

import os
from pyomo.environ import SolverFactory

# IDAES places the binary here by default
ipopt_path = os.path.expanduser('~/.idaes/bin/ipopt')

if os.path.exists(ipopt_path):
    solver = SolverFactory('ipopt', executable=ipopt_path)
    print(f"✓ IPOPT found at: {ipopt_path}")
    print("✓ Solver is ready — let's optimize!")
else:
    # Search the whole system for the binary
    import subprocess
    result = subprocess.run(
        ['find', '/root', '-name', 'ipopt', '-type', 'f'],
        capture_output=True, text=True
    )
    print("Search result:", result.stdout if result.stdout else "Not found")
    print("→ Run !idaes get-extensions in a new cell, then re-run this cell")

# Phase 1: Blending Optimization

from pyomo.environ import(
    ConcreteModel, Var, NonNegativeReals,
    Objective, Constraint, minimize, SolverFactory
)
import os

# Solver path
ipopt_path = os.path.expanduser('~/.idaes/bin/ipopt')
solver = SolverFactory('ipopt', executable=ipopt_path)

model = ConcreteModel()

# Decision variables: how much of each stream to purchase
model.x_A = Var(domain=NonNegativeReals)  # kg of Stream A @ €3/kg
model.x_B = Var(domain=NonNegativeReals)  # kg of Stream B @ €5/kg

# Objective: minimize total purchase cost
model.cost = Objective(
    expr  = 3 * model.x_A + 5 * model.x_B,
    sense = minimize
)

# Constraint 1: need at least 100 kg of product
model.min_product = Constraint(expr = model.x_A + model.x_B >= 100)

# Constraint 2: Stream A supplier can only send 80 kg max
model.max_A = Constraint(expr = model.x_A <= 80)

# Constraint 3: Stream B supplier can only send 60 kg max
model.max_B = Constraint(expr = model.x_B <= 60)

# Constraint 4: product quality - at least 40% must be Stream B
# Rearranged from: x_B / (x_A + x_B) >= 0.40
# To avoid division: 0.6 * x_B >= 0.4 * x_A
model.quality = Constraint(expr = 0.6 * model.x_B >= 0.4 * model.x_A)

result = solver.solve(model, tee=False)

xA = model.x_A()
xB = model.x_B()

print("=" * 44)
print(" BLENDING OPTIMIZATION - RESULTS")
print("=" * 44)
print(f" Stream A purchased : {xA:.2f} kg @ €3/kg")
print(f" Stream B purchased : {xB:.2f} kg @ €5/kg")
print(f" Total product      : {xA + xB:.2f} kg")
print(f" Minimum cost       : €{3*xA + 5*xB:.2f}")
print(f" Stream B fraction  : {xB/(xA+xB):.1%}  (requirement: >=40%)")
print("=" * 44)
print(f"\n Solver status: {result.solver.termination_condition}")

# Tighten quality: now Stream B must be >= 60% of product

model2 = ConcreteModel()
model2.x_A = Var(domain=NonNegativeReals)
model2.x_B = Var(domain=NonNegativeReals)

model2.cost = Objective(expr = 3*model2.x_A + 5*model2.x_B, sense=minimize)
model2.min_product = Constraint(expr = model2.x_A + model2.x_B >= 100)
model2.max_A = Constraint(expr = model2.x_A <= 80)
model2.max_B = Constraint(expr = model2.x_B <= 60)

# Changed: Stream B must now be at least 60% (was 40%)
model2.quality = Constraint(expr = 0.4 * model2.x_B >= 0.6 * model2.x_A)

solver.solve(model2, tee=False)

xA2 = model2.x_A.value
xB2 = model2.x_B.value
cost1 = 3*xA + 5*xB
cost2 = 3*xA2 + 5*xB2

print("=" * 44)
print(" EFFECT OF TIGHTENING QUALITY SPEC")
print("=" * 44)
print(f" {'':20s} {'40% B':>8s} {'60% B':>8s}")
print(f" {'-'*38}")
print(f" {'Stream A (kg)':20s} {xA:>8.2f} {xA2:>8.2f}")
print(f" {'Stream B (kg)':20s} {xB:>8.2f} {xB2:>8.2f}")
print(f" {'Total cost (€)':20s} {cost1:>8.2f} {cost2:>8.2f}")
print(f" {'Cost increase (€)':20s} {'-':>8s} {cost2-cost1:>8.2f}")
print("=" * 44)
print(f"\n Stricter quality costs €{cost2-cost1:.2f} more")
print(f"\n This is the quality-cost trade-off optimization reveals")

# Phase 2: CSTR Operating Cost Minimization

import idaes

from pyomo.environ import(
    ConcreteModel, Var, Objective, Constraint,
    minimize, SolverFactory, exp, value
)
import os

ipopt_path = os.path.expanduser('~/.ideas/bin/ipopt')
solver = SolverFactory('ipopt')

# Process parameters
k0  = 1e8          # pre-exponential factor   [1/s]
Ea  = 65000        # activation energy        [J/mol]
R   = 8.314        # gas constant             [J/mol.K]
C_A0  = 2.0        # feed concentration       [mol/L]
F_A0  = 5.0        # molar feed rate          [mol/s]
V     = 500.0      # reactor volume           [L]  - fixed, given

model = ConcreteModel()

# Decision variables
model.T = Var(bounds=(300, 450),  initialize=350)       # Temperature [K]
model.X = Var(bounds=(0.01, 0.999),  initialize=0.8)    # Conversion  [-]

# Objective function
# Heating cost: proportional to temperature rise above 298 K (ambient)
# Revenue loss: cost of feed leaving reactor unreacted
model.obj = Objective(
    expr  = 0.5 * (model.T - 298) + 100.0 * (1 - model.X),
    sense = minimize
)

# Constraints
# 1. CSTR material balance (equality)
# Rate of A converted = rate of reaction in reactor
# F_A0 * X = k(T) * C_A0 * (1-X) * V
model.cstr_balance = Constraint(
    expr = F_A0 * model.X ==
    k0 * exp(-Ea / (R * model.T)) * C_A0 * (1 - model.X) * V
)

# 2. Minimum conversion spec (product quality requirement)
model.min_conversion = Constraint(expr = model.X >= 0.80)
result = solver.solve(model, tee=False)

T_opt    = value(model.T)
X_opt    = value(model.X)
heat_cost = 0.5 * (T_opt - 298)
rev_loss  = 100.0 * (1 - X_opt)
total     = heat_cost + rev_loss

print("=" * 52)
print("  CSTR OPTIMIZATION - OPTIMAL SOLUTION")
print("=" * 52)
print(f"  Optimal temperature  : {T_opt:.1f} K ({T_opt-273.15:.1f} degC)")
print(f"  Optimal conversion   : {X_opt:.4f}  ({X_opt*100:.2f}%)")
print(f"  ___________________________________________")
print(f"  Heating cost          : €{heat_cost:.2f}/hr")
print(f"  Revenue loss (waste)  : €{rev_loss:.2f}/hr")
print(f"  Total minimum cost    : €{total:.2f}/hr")
print("=" * 52)
print(f"   Solver status : {result.solver.termination_condition}")

import numpy as np
import matplotlib.pyplot as plt
from pyomo.environ import value

k0, Ea, R   = 1e8, 65000, 8.314
C_A0, F_A0, V  = 2.0, 5.0, 500.0

T_opt = 364.5
X_opt = 0.9063
total = 0.5 * (T_opt - 298) + 100.0 * (1 - X_opt)
# Compute cost at every temperature from 300 to 450 K
T_range = np.linspace(300, 450, 300)
X_values, cost_values, heat_costs, rev_losses = [], [], [], []

T_arr = np.linspace(300, 450, 300)
hc_arr = np.zeros(300)
rl_arr = np.zeros(300)
tc_arr = np.zeros(300)
Xc_arr = np.zeros(300)


for i in range(300):
    T    = T_arr[i]
    k    = k0 * np.exp(-Ea / (R * T))
    Da   = k * C_A0 * V / F_A0
    X    = Da / (1 + Da)
    hc_arr[i] = 0.5 * (T - 298)
    rl_arr[i] = 100.0 * (1 - X)
    tc_arr[i] = hc_arr[i] + rl_arr[i]
    Xc_arr[i] = X * 100

    print(f"T_arr: {T_arr.shape}  |  tc_arr: {tc_arr.shape}")
    # Plot
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle("CSTR Operating Cost Optimization  |  A -> B", fontsize=13, fontweight='bold')

    # Left plot: cost breakdown
    ax1 = axes[0]
    ax1.plot(T_arr, tc_arr, 'k-', linewidth=2.5, label='Total cost')
    ax1.plot(T_arr, hc_arr, 'r--', linewidth=1.5, label='Heating cost')
    ax1.plot(T_arr, rl_arr, 'b--', linewidth=1.5, label='Revenue loss (waste)')
    ax1.axvline(T_opt, color='green', linewidth=2, linestyle=':', label=f'Optimal T = {T_opt:.1f} K')
    ax1.scatter([T_opt], [total], color='green', zorder=5, s=80)
    ax1.set_xlabel('Temperature [K]'); ax1.set_ylabel('Cost [€/hr]')
    ax1.set_title('Cost Trade-off'); ax1.legend(fontsize=9); ax1.grid(alpha=0.3)
    ax1.annotate(f' Min cost\n  €{total:.1f}/hr\n  T={T_opt:.0f}K',
                xy=(T_opt, total), xytext=(T_opt+15, total+5), fontsize=9, color='green')

    # Right plot: conversion curve
    ax2 = axes[1]
    ax2.plot(T_arr, Xc_arr, 'purple', lw=2.5, label='Conversion X')
    ax2.axhline(80, color='orange', ls='--', lw=1.5, label='Min spec (80%)')
    ax2.axvline(T_opt, color='green', lw=2, ls=':', label=f'Optimal T={T_opt} K')
    ax2.scatter([T_opt], [X_opt*100], color='green', zorder=5, s=80)
    ax2.set_xlabel('Temperature [K]'); ax2.set_ylabel('Conversion [%]')
    ax2.set_title('Conversion vs Temperature')
    ax2.legend(fontsize=9); ax2.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig('cstr_optimization.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Plot saved as cstr_optimization.png")

# Sensitivity Analysis

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize as sci_min

# Fixed parameters
k0=1e8; Ea=65000; R=8.314; C_A0=2.0; F_A0=5.0

def solve_cstr(V, X_MIN=0.80):

    def objective(vars):
        T, X = vars
        return 0.5*(T - 298) + 100.0*(1 - X)

    def cstr_balance(vars):
        # Must equal zero: CSTR material balance
        T, X = vars
        k = k0 * np.exp(-Ea / (R * T))
        return F_A0*X - k*C_A0*(1 - X)*V

    def min_conv(vars):
        # Must be >= 0: conversion spec
        return vars[1] - X_MIN

    result = sci_min(
        fun         = objective,
        x0          = [350.0, 0.85],          # initial guess
        method      = 'SLSQP',
        bounds      = [(300, 450), (0.01, 0.999)],
        constraints = [
            {'type': 'eq',   'fun': cstr_balance},
            {'type': 'ineq', 'fun': min_conv}
        ],
        options = {'ftol': 1e-9, 'maxiter': 500}
    )
    return result.x[0], result.x[1], result.fun

# Part 1: vary reactor volume
V_range    = np.linspace(100, 1000, 30)
T_v, X_v, cost_v = [], [], []

for V in V_range:
    T_opt, X_opt, c_opt = solve_cstr(V, X_MIN=0.80)
    T_v.append(T_opt)
    X_v.append(X_opt * 100)
    cost_v.append(c_opt)

T_v = np.array(T_v); X_v = np.array(X_v); cost_v = np.array(cost_v)
print(f"Arrays built — V:{V_range.shape}, T:{T_v.shape}, cost:{cost_v.shape}")

# Part 2: vary conversion spec
Xmin_range  = np.linspace(0.60, 0.95, 30)
T_x, cost_x = [], []

for xmin in Xmin_range:
    T_opt, X_opt, c_opt = solve_cstr(V=500.0, X_MIN=xmin)
    T_x.append(T_opt)
    cost_x.append(c_opt)

T_x = np.array(T_x); cost_x = np.array(cost_x)
print(f"Arrays built — Xmin:{Xmin_range.shape}, T:{T_x.shape}, cost:{cost_x.shape}")

#  Plot all 4 panels
fig, axes = plt.subplots(2, 2, figsize=(13, 9))
fig.suptitle("CSTR Sensitivity Analysis", fontsize=14, fontweight='bold')

base_v = np.argmin(np.abs(V_range - 500))
base_x = np.argmin(np.abs(Xmin_range - 0.80))

# Panel 1: Optimal T vs Volume
ax = axes[0,0]
ax.plot(V_range, T_v, 'b-o', ms=4, lw=2)
ax.scatter([V_range[base_v]], [T_v[base_v]], color='red', s=80, zorder=5, label='Base (500L)')
ax.set_xlabel('Reactor Volume [L]'); ax.set_ylabel('Optimal Temperature [K]')
ax.set_title('Optimal T vs Reactor Volume'); ax.legend(); ax.grid(alpha=0.3)

# Panel 2: Optimal Cost vs Volume
ax = axes[0,1]
ax.plot(V_range, cost_v, 'r-o', ms=4, lw=2)
ax.scatter([V_range[base_v]], [cost_v[base_v]], color='blue', s=80, zorder=5, label='Base (500L)')
ax.set_xlabel('Reactor Volume [L]'); ax.set_ylabel('Min Cost [€/hr]')
ax.set_title('Cost vs Reactor Volume'); ax.legend(); ax.grid(alpha=0.3)

# Panel 3: Optimal T vs Conversion Spec
ax = axes[1,0]
ax.plot(Xmin_range*100, T_x, 'b-o', ms=4, lw=2)
ax.scatter([80], [T_x[base_x]], color='red', s=80, zorder=5, label='Base (80%)')
ax.set_xlabel('Min Conversion Spec [%]'); ax.set_ylabel('Optimal Temperature [K]')
ax.set_title('Optimal T vs Conversion Spec'); ax.legend(); ax.grid(alpha=0.3)

# Panel 4: Optimal Cost vs Conversion Spec
ax = axes[1,1]
ax.plot(Xmin_range*100, cost_x, 'r-o', ms=4, lw=2)
ax.scatter([80], [cost_x[base_x]], color='blue', s=80, zorder=5, label='Base (80%)')
ax.set_xlabel('Min Conversion Spec [%]'); ax.set_ylabel('Min Cost [€/hr]')
ax.set_title('Cost vs Conversion Spec'); ax.legend(); ax.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('sensitivity_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

# Print insight summary
print("\n" + "="*52)
print("  SENSITIVITY INSIGHTS")
print("="*52)
print(f"  Volume effect:")
print(f"    V=100L  → T_opt={T_v[0]:.1f}K, cost=€{cost_v[0]:.2f}/hr")
print(f"    V=500L  → T_opt={T_v[base_v]:.1f}K, cost=€{cost_v[base_v]:.2f}/hr")
print(f"    V=1000L → T_opt={T_v[-1]:.1f}K, cost=€{cost_v[-1]:.2f}/hr")
print(f"\n  Conversion spec effect:")
print(f"    X=60%  → T_opt={T_x[0]:.1f}K, cost=€{cost_x[0]:.2f}/hr")
print(f"    X=80%  → T_opt={T_x[base_x]:.1f}K, cost=€{cost_x[base_x]:.2f}/hr")
print(f"    X=95%  → T_opt={T_x[-1]:.1f}K, cost=€{cost_x[-1]:.2f}/hr")
print("="*52)

import os, glob

pngs = glob.glob('/content/*.png')
for f in sorted(pngs, key=os.path.getmtime):
    print(f"{os.path.getmtime(f):.0f}  {f}")